import { Analysis, formatTime } from "./analysis";
import {
  DistanceUnit,
  distanceUnitLabels,
  formatPaceForUnit,
  formatSpeedForUnit,
  secondsPerDistanceUnit,
} from "./units";

export function buildReportExportText(
  analysis: Analysis,
  generatedDate: string,
  distanceUnit: DistanceUnit = "km",
) {
  const averageRunPace = formatPaceForUnit(
    analysis.averageRunSeconds,
    analysis.raceFormat,
    distanceUnit,
  );
  const averageRunSpeed = formatSpeedForUnit(
    analysis.averageRunSeconds,
    analysis.raceFormat,
    distanceUnit,
  );
  const runFadePace = secondsPerDistanceUnit(
    analysis.runFadeSeconds,
    analysis.raceFormat,
    distanceUnit,
  );
  const topLeaks = analysis.topLeaks
    .map(
      (leak, index) =>
        `${index + 1}. ${leak.label}: ${formatTime(leak.recoverableSeconds)} realistic gain. ${leak.detail}.`,
    )
    .join("\n");
  const priorities = analysis.priorities
    .map((priority, index) => `${index + 1}. ${priority}`)
    .join("\n");
  const trainingPlan = analysis.trainingPlan
    .map(
      (week) =>
        `Week ${week.week} - ${week.focus}\n${week.sessions
          .map((session) => `- ${session}`)
          .join("\n")}\nTarget: ${week.target}`,
    )
    .join("\n\n");
  const stationRanking = analysis.stationResults
    .map(
      (station, index) =>
        `${index + 1}. ${station.label}: ${formatTime(station.seconds)} split, ${formatTime(station.benchmark)} ${analysis.levelLabel.toLowerCase()} benchmark, ${formatTime(station.gap)} leak.`,
    )
    .join("\n");

  return [
    "Ocht Race Report",
    generatedDate ? `Generated ${generatedDate}` : "Generated by Ocht",
    "",
    analysis.report,
    "",
    `Athlete level: ${analysis.levelLabel}`,
    analysis.stationBenchmarkSummary,
    "",
    "Key Metrics",
    `Projected finish: ${formatTime(analysis.finishSeconds)}`,
    `Next target: ${formatTime(analysis.predictedTargetSeconds)}`,
    `Recoverable time: ${formatTime(analysis.recoverableSeconds)}`,
    `Average run pace: ${averageRunPace} (${averageRunSpeed})`,
    `Run fade: ${formatTime(runFadePace)}/${distanceUnitLabels[distanceUnit]}`,
    `Target gap: ${formatTime(analysis.targetGapSeconds)}`,
    "",
    "Target Math",
    `Target difficulty: ${analysis.targetDifficultyLabel}`,
    `Required gain: ${formatTime(analysis.requiredGainSeconds)} (${Math.round(analysis.requiredGainPercent * 1000) / 10}%)`,
    `Run-only route: ${formatTime(analysis.requiredGainPerRunSeconds)} from each run`,
    `Station-only route: ${formatTime(analysis.requiredGainPerStationSeconds)} from each station`,
    `Balanced targets: ${formatTime(analysis.targetRunAverageSeconds)} average run, ${formatTime(analysis.targetStationAverageSeconds)} average station`,
    analysis.targetPlanSummary,
    "",
    "Top Time Leaks",
    topLeaks,
    "",
    "Training Priorities",
    priorities,
    "",
    "Four-Week Focus",
    trainingPlan,
    "",
    "Station Ranking",
    stationRanking,
  ].join("\n");
}
